image: wadoon/key-test-docker:docs

pages:
  script:
    - mkdocs build  
    - mv site public 
    - linkchecker -F html -t 5 --no-robots public/index.html || true
    - mv linkchecker-out.html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
