site_name: KeY Developer Documentation
site_url: https://keyproject.github.io/key-docs/

plugins:
  - search
  - bibtex:
      bib_file: "refs.bib"
#      csl_file: "springer-basic-author-date.csl"
  
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.highlight
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
            #          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
  - markdown_aafigure:
      format: svg
  - markdown_blockdiag:
      format: svg

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js'
#   - "js/javajml.js"

#copyright: Copyright &copy; 2016 - 2020 Martin Donath

theme: # material theme
  name: material
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: 'blue grey'
      accent: 'teal'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: 'dark'
      accent: 'orange'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.annotate

  icon:
    repo: fontawesome/brands/github

#  palette:
#    primary: 'blue grey'
#    accent: 'teal'
    

nav:
  - Home: index.md
  - User Guide:
      - user/index.md
      - changelog.md
      - user/FAQ.md
      - user/ADTs.md
      - user/Classpath.md
      - user/Interactive.md
      - user/JavaDLinJML.md
      - user/RemoveGenerics.md
      - user/Polarity.md
      - user/JavaGrammar.md
      - Quicktour:
          - user/quicktour/index.md
          - user/quicktour/install.md
          - user/quicktour/loading.md
          - user/quicktour/proving.md
          - user/quicktour/appendix.md
      - UI Features:
          - user/Exploration.md
          - user/NodeDiff.md
          - user/ProofSlicing.md
          - user/ProofCaching.md
          - user/ProofReordering.md
      - Languages:
          - user/HowToTaclet.md
          - user/JMLGrammar.md
          - user/KeyGrammar.md
      - Proof Scripts:
          - workbench/Proof Scripts/index.md
          - workbench/Proof Scripts/commands.md
          - workbench/Proof Scripts/language.md
          - workbench/Proof Scripts/linearScripts.md
          - workbench/Proof Scripts/macros.md
          - workbench/Proof Scripts/variables.md

  - KeYclipse:
      - "Overview": eclipse/index.md
      - "KeY basics": eclipse/CrossProject/index.md
      - "SED": eclipse/SED/index.md
      - "Stubby": eclipse/Stubby/index.md
      - "KeY IDE": eclipse/KeYIDE/index.md
      - "MonKeY": eclipse/MonKeY/index.md
      - "Starter": eclipse/Starter/index.md
      - "VisualDBC": eclipse/VisualDbC/index.md
      - "JML Editing": eclipse/JMLEditing/index.md
      - "Resources" : eclipse/KeYResources/index.md

  - Development:
      - "Start": devel/index.md
      - Basics:
          - devel/CodingConventions.md
          - devel/SpotlessAutomaticFormatting.md
          - devel/ExternalProject.md
          - devel/Gradle.md
          - devel/Logging.md
      - Important topics:
        - devel/GUIExtensions.md
        - devel/Listeners.md
        - devel/HowtoTaclet.md
        - devel/ProofLoadSave.md
      - SMT:
          - devel/AddingSMTSolvers.md
          - devel/SMTTranslation.md
          - devel/CounterExampleGeneration.md
      - devel/How2ExtRecoder.md
      - Testing:
          - devel/Testing/index.md
          - devel/Testing/ProveRules.md
          - devel/Testing/RunAllProves.md
          - devel/Testing/deterministicTestOrder.md
          - devel/Testing/parserMessageTest.md
      - Write Documentation: "devel/howtodoc/index.md"


  
#  nav_style: dark
#  logo: 'https://git.key-project.org/uploads/-/system/appearance/logo/1/key-color.png'
  #feature:
  #  tabs: true
repo_name: key-docs
repo_url: https://github.com/KeYProject/key-docs/
edit_uri: edit/master/docs/
